### ISSUE TITLE
Main CDK module is not able to import other local modules

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre-cdk-handler#11]
The main sceptre CDK module is not able to import any other modules.  I'm getting a `ModuleNotFoundError` when attempting to do the import.   Tried importing using both relative and non-relative notations and both fail.  My entire sceptre test project can be downloaded from https://file.io/J0yCGEMdQEdx

My project:

➜  testprojB tree

```
.
├── config
│   ├── config.yaml
│   └── develop
│       ├── app.yaml
│       └── config.yaml
├── package-lock.json
├── package.json
├── requirements-dev.txt
├── requirements.txt
└── templates
    ├── __init__.py
    ├── __pycache__
    │   └── app.cpython-39.pyc
    ├── app.py
    └── my_project
        ├── __init__.py
        └── my_project_stack.py

```

➜  testprojB cat templates/app.py
```
from aws_cdk import CfnParameter
from sceptre_cdk_handler import SceptreCdkStack
from my_project.my_project_stack import MyProjectStack

# Important: Notice how it subclasses SceptreCdkStack and passes **kwargs into the base class's
# __init__(). This is important to maintain compability with the different deployment_types.
class MyAppStack(SceptreCdkStack):
    def __init__(self, scope, id: str, sceptre_user_data: dict, **kwargs):
        super().__init__(scope, id, sceptre_user_data, **kwargs)
        # If you want to pass parameters like you do elsewhere in Sceptre, this works great!
        self.special_parameter = CfnParameter(self, 'SpecialEnv')
        self.my_project_stack = MyProjectStack(self)
```

Sceptre execution:
```
➜  testprojB AWS_PROFILE=itsandbox-admin AWS_DEFAULT_REGION=us-east-1 sceptre generate develop/app.yaml
testprojB@ /Users/zaro0508/work-sage/testprojB
└── cdk-assets@2.63.0

Traceback (most recent call last):
  File "/Users/zaro0508/.pyenv/versions/py39-data_curator-infra/bin/sceptre", line 8, in <module>
    sys.exit(cli())
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/sceptre/cli/helpers.py", line 42, in decorated
    return func(*args, **kwargs)
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/sceptre/cli/template.py", line 89, in generate_command
    responses = plan.generate()
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/sceptre/plan/plan.py", line 387, in generate
    return self._execute(*args)
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/sceptre/plan/plan.py", line 29, in wrapped
    return func(self, *args, **kwargs)
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/sceptre/plan/plan.py", line 56, in _execute
    return executor.execute(*args)
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/sceptre/plan/executor.py", line 52, in execute
    stack, status = future.result()
  File "/Users/zaro0508/.pyenv/versions/3.9.7/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Users/zaro0508/.pyenv/versions/3.9.7/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/zaro0508/.pyenv/versions/3.9.7/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/sceptre/plan/executor.py", line 59, in _execute
    result = getattr(actions, self.command)(*args)
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/sceptre/hooks/__init__.py", line 104, in decorated
    response = func(self, *args, **kwargs)
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/sceptre/plan/actions.py", line 641, in generate
    return self.stack.template.body
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/sceptre/template.py", line 90, in body
    body = handler.handle()
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/sceptre_cdk_handler/cdk.py", line 157, in handle
    stack_class: Type[SceptreCdkStack] = self._importer.import_class(self.cdk_template_path, self.cdk_class_name)
  File "/Users/zaro0508/.pyenv/versions/3.9.7/envs/py39-data_curator-infra/lib/python3.9/site-packages/sceptre_cdk_handler/class_importer.py", line 31, in import_class
    loader.exec_module(template_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/zaro0508/work-sage/testprojB/templates/app.py", line 3, in <module>
    from my_project.my_project_stack import MyProjectStack
ModuleNotFoundError: No module named 'my_project'
```

**Comment by jfalkenstein** [comment]
This has been resolved.
