### ISSUE TITLE
A Python Stack Trace Error Occurs If `deployment_type` is not Specified

### ISSUE THREAD

**Issue by X-Guardian** [Sceptre/sceptre-cdk-handler#14]
### Subject of the issue

If the `deployment_type` property is not specified on the `template` object. The CDK handler errors with a full Python stack trace.

### Your environment

- `sceptre-cdk-handler v2.0.0`

### Expected Behaviour

The handler should return a managed error with a message like:

```
[2023-03-03 16:49:03] - dev/cdk - Launching Stack
[2023-03-03 16:49:03] - dev/cdk - Stack is in the PENDING state
[2023-03-03 16:49:03] - dev/cdk - Creating Stack
sceptre-example@ C:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\sceptre-example
└── (empty)

C:\Program Files\nodejs -> .\
└── cdk-assets@2.59.0

[2023-03-03 16:49:03] - dev/cdk - 'deployment_type' is a required property for a template type of 'cdk'
```

### Actual behaviour

```
[2023-03-03 16:49:03] - dev/cdk - Launching Stack
[2023-03-03 16:49:03] - dev/cdk - Stack is in the PENDING state
[2023-03-03 16:49:03] - dev/cdk - Creating Stack
sceptre-example@ C:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\sceptre-example
└── (empty)

C:\Program Files\nodejs -> .\
└── cdk-assets@2.59.0

Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\Scripts\sceptre.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\cli\helpers.py", line 43, in decorated
    return func(*args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\cli\launch.py", line 62, in launch_command
    exit_code = launcher.launch(prune)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\cli\launch.py", line 105, in launch
    code = code or self._deploy(deploy_plan)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\cli\launch.py", line 197, in _deploy
    result = deploy_plan.launch()
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\plan.py", line 170, in launch
    return self._execute(*args)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\plan.py", line 29, in wrapped
    return func(self, *args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\plan.py", line 55, in _execute
    return executor.execute(*args)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\executor.py", line 52, in execute
    stack, status = future.result()
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\executor.py", line 59, in _execute
    result = getattr(actions, self.command)(*args)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\hooks\__init__.py", line 107, in decorated
    response = func(self, *args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\actions.py", line 213, in launch
    status = self.create()
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\hooks\__init__.py", line 107, in decorated
    response = func(self, *args, **kwargs)
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\plan\actions.py", line 91, in create
    create_stack_kwargs.update(self.stack.template.get_boto_call_parameter())
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\template.py", line 224, in get_boto_call_parameter
    return {"TemplateBody": self.body}
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre\template.py", line 96, in body
    handler.validate()
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre_cdk_handler\cdk.py", line 178, in validate
    if self.deployment_type == 'bootstrapped' and self.bootstrapless_config:
  File "c:\Users\Simon\Documents\GitHub\Sceptre\sceptre-cdk-handler\.venv\lib\site-packages\sceptre_cdk_handler\cdk.py", line 147, in deployment_type
    return self.arguments['deployment_type']
KeyError: 'deployment_type'
```

**Comment by jfalkenstein** [comment]
Yeah, that's a good catch. We should probably handle this specific situation in the validation. Since this on my dev branch that hasn't been merged yet, I'll fix this there.

**Comment by jfalkenstein** [comment]
Actually, it's weird... this should be caught by the json schema validation...

**Comment by jfalkenstein** [comment]
I figured it out. The handler is currently calling super().validate() at the END of what it does. If I move that up to the beginning, that validation is caught properly.

**Comment by jfalkenstein** [comment]
This is going to be fixed in this commit: https://github.com/Sceptre/sceptre-cdk-handler/pull/10/commits/0e2fa7406cd7595ad4883db43cd285dee8824951

Since this is ultimately a matter of resolving an issue in #10 , I'm going to close this issue, but I've resolved it on that branch.

**Comment by X-Guardian** [comment]
No stack trace now, but the error is still pretty ugly:

```
[2023-03-04 19:22:29] - dev/cdk - Launching Stack
[2023-03-04 19:22:29] - dev/cdk - Stack is in the CREATE_COMPLETE state
[2023-03-04 19:22:29] - dev/cdk - Updating Stack
"'deployment_type' is a required property\n\nFailed validating 'required' in schema:\n    {'additionalProperties': False,\n     'properties': {'bootstrap_qualifier': {'type': 'string'},\n                    'bootstrapless_config': {'additionalProperties': False,\n                                             'properties': {'file_asset_bucket_name': {'type': 'string'},\n                                                            'file_asset_prefix': {'type': 'string'},\n                                        
                    'file_asset_publishing_role_arn': {'type': 'string'},\n                                                            'file_asset_region_set': {'type': 'string'},\n                                                            'image_asset_account_id': {'type': 'string'},\n                                                      
      'image_asset_publishing_role_arn': {'type': 'string'},\n                                                            'image_asset_region_set': {'type': 'string'},\n                                                            'image_asset_repository_name': {'type': 'string'},\n                                                            'image_asset_tag_prefix': {'type': 'string'},\n                                                            'template_bucket_name': {'type': 'string'}},\n                   
                          'type': 'object'},\n                    'class_name': {'type': 'string'},\n                    'context': {'type': 'object'},\n                  
  'deployment_type': {'enum': ['bootstrapped',\n                                                 'bootstrapless'],\n                                        'type': 'string'},\n                    'path': {'type': 'string'},\n                    'stack_logical_id': {'type': 'string'}},\n     'required': ['path', 'deployment_type'],\n     'type': 'object'}\n\nOn instance:\n    {'class_name': 'CdkStack',\n     'context': {'@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver': True,\n              
   '@aws-cdk/aws-apigateway:disableCloudWatchRole': True,\n                 '@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName': True,\n                 
'@aws-cdk/aws-ec2:uniqueImdsv2TemplateName': True,\n                 '@aws-cdk/aws-ecs:arnFormatIncludesClusterName': True,\n                 '@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker': True,\n                 '@aws-cdk/aws-events:eventsTargetQueueSameAccount': True,\n                 '@aws-cdk/aws-iam:minimizePolicies': True,\n                 '@aws-cdk/aws-iam:standardizedServicePrincipals': True,\n                 '@aws-cdk/aws-lambda:recognizeLayerVersion': True,\n           
      '@aws-cdk/aws-s3:createDefaultLoggingPolicy': True,\n                 '@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption': True,\n                 '@aws-cdk/core:bootstrapQualifier': 'hnb659fds',\n                 '@aws-cdk/core:checkSecretUsage': True,\n                 '@aws-cdk/core:enablePartitionLiterals': True,\n            
     '@aws-cdk/core:target-partitions': ['aws', 'aws-cn'],\n                 '@aws-cdk/core:validateSnapshotRemovalPolicy': True},\n     'path': 'CDK/s3.py'}"
```
